apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xfah
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xfah
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xfah
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xfah
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xfah
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ornr-tenant/rhtap-demo-app/hacbs-test-project-xfah@sha256:61b2c8af57a863eb89151d0d1b3c322dc3e076a4bc6d737b0c5c3ea3613ed9f3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
